In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('../DATA/HYG-Database/hyg/CURRENT/hygdata_v41.csv')

In [4]:
data

,id,hip,hd,hr,gl,bf,proper,ra,dec,dist,...,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max
0,0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.0000,...,NaN,NaN,NaN,1,0,NaN,1.000000e+00,NaN,NaN,NaN
1,1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,...,NaN,NaN,Psc,1,1,NaN,9.638290e+00,NaN,NaN,NaN
2,2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,...,NaN,NaN,Cet,1,2,NaN,3.922835e-01,NaN,NaN,NaN
3,3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,...,NaN,NaN,And,1,3,NaN,3.869011e+02,NaN,NaN,NaN
4,4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,...,NaN,NaN,Phe,1,4,NaN,9.366989e+00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119621,119626,NaN,124953.0,5343.0,NaN,NaN,NaN,14.267833,18.911944,100000.0000,...,NaN,NaN,Boo,1,119626,NaN,3.531832e+07,CN,6.01,5.98
119622,119627,NaN,152249.0,6263.0,NaN,NaN,NaN,16.903278,-41.850278,100000.0000,...,NaN,NaN,Sco,1,119627,NaN,2.290868e+07,NaN,NaN,NaN
119623,119628,NaN,162678.0,6660.0,NaN,NaN,NaN,17.895972,-34.786111,100000.0000,...,NaN,NaN,Sco,1,119628,NaN,2.443431e+07,NaN,NaN,NaN
119624,119629,NaN,168021.0,6848.0,NaN,NaN,NaN,18.312028,-18.619444,100000.0000,...,NaN,NaN,Sgr,1,119629,NaN,1.599558e+07,NaN,NaN,NaN
119625,119630,NaN,224960.0,9090.0,NaN,NaN,NaN,0.035361,-14.676111,100000.0000,...,NaN,NaN,Cet,1,119630,NaN,1.258925e+07,W,14.80,7.10

In [25]:
df = data.dropna(subset=['hip'], how='all')

In [26]:
df = df.set_index('id') # изначально было bf/bayer, но даже в них не хватало некоторых звезд

In [27]:
df

,hip,hd,hr,gl,bf,proper,ra,dec,dist,pmra,...,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max
id,,,,,,,,,,,,,,,,,,,,,
1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,-5.20,...,NaN,NaN,Psc,1,1,NaN,9.638290,NaN,NaN,NaN
2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,181.21,...,NaN,NaN,Cet,1,2,NaN,0.392283,NaN,NaN,NaN
3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,5.24,...,NaN,NaN,And,1,3,NaN,386.901132,NaN,NaN,NaN
4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,62.85,...,NaN,NaN,Phe,1,4,NaN,9.366989,NaN,NaN,NaN
5,5.0,224705.0,NaN,NaN,NaN,NaN,0.000665,-40.591202,257.7320,2.53,...,NaN,NaN,Phe,1,5,NaN,21.998851,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117950,118318.0,224673.0,NaN,NaN,NaN,NaN,23.997583,11.673714,398.4064,-2.16,...,NaN,NaN,Peg,1,117950,NaN,221.207578,NaN,NaN,NaN
117951,118319.0,224693.0,NaN,NaN,NaN,Axólotl,23.998285,-22.428113,98.4252,148.74,...,NaN,NaN,Cet,1,117951,NaN,4.309233,NaN,NaN,NaN
117952,118320.0,224689.0,NaN,NaN,NaN,NaN,23.998407,5.956552,178.8909,20.92,...,NaN,NaN,Psc,1,117952,NaN,25.656653,NaN,NaN,NaN
117953,118321.0,224685.0,NaN,NaN,NaN,NaN,23.998584,-64.372313,53.0786,216.99,...,NaN,NaN,Tuc,1,117953,NaN,0.512861,NaN,NaN,NaN
117954,118322.0,224686.0,9076.0,NaN,Eps Tuc,NaN,23.998594,-65.577132,114.4165,48.63,...,Eps,NaN,Tuc,1,117954,NaN,182.305596,NaN,NaN,NaN

In [28]:
df.iloc[1].T

hip                   2.0
hd               224690.0
hr                    NaN
gl                    NaN
bf                    NaN
proper                NaN
ra               0.000283
dec             -19.49884
dist              47.9616
pmra               181.21
pmdec               -0.93
rv                    0.0
mag                  9.27
absmag              5.866
spect                 K3V
ci                  0.999
x               45.210918
y                0.003365
z              -16.008996
vx                   -0.0
vy               0.000042
vz                   -0.0
rarad            0.000074
decrad          -0.340319
pmrarad          0.000001
pmdecrad             -0.0
bayer                 NaN
flam                  NaN
con                   Cet
comp                    1
comp_primary            2
base                  NaN
lum              0.392283
var                   NaN
var_min               NaN
var_max               NaN
Name: 2, dtype: object

In [29]:
df = df[['hip', 'hd', 'hr', 'gl', 'bf', 'proper', 'ra', 'dec', 'dist', 'mag', 'spect', 'bayer', 'flam', 'con', 'lum']]

In [30]:
df.to_csv('naked_df.csv', index=True)

In [31]:
df['con'].unique()

array(['Psc', 'Cet', 'And', 'Phe', 'Peg', 'Scl', 'Cas', 'Oct', 'Cep',
       'Tuc', 'Hyi', 'UMi', 'Eri', 'Per', 'Tri', 'For', 'Ari', 'Hor',
       'Ret', 'Cam', 'Men', 'Tau', 'Dor', 'Cae', 'Pic', 'Aur', 'Ori',
       'Lep', 'Col', 'Mon', 'Gem', 'Car', 'Pup', 'CMa', 'Lyn', 'Vol',
       'CMi', 'Cha', 'Cnc', 'Vel', 'UMa', 'Hya', 'Pyx', 'Leo', 'LMi',
       'Dra', 'Ant', 'Sex', 'Crt', 'Cen', 'Mus', 'Vir', 'Cru', 'Crv',
       'Com', 'CVn', 'Boo', 'Cir', 'Aps', 'Lup', 'Lib', 'TrA', 'Ser',
       'Nor', 'CrB', 'Sco', 'Her', 'Oph', 'Ara', 'Pav', 'Sgr', 'CrA',
       'Tel', 'Lyr', 'Sct', 'Aql', 'Sge', 'Vul', 'Cyg', 'Cap', 'Del',
       'Mic', 'Ind', 'Aqr', 'Equ', 'PsA', 'Gru', 'Lac'], dtype=object)

In [ ]:
def plot_constellation_centered(frame, markdown):
    """
    frame: DataFrame with 'ra', 'dec', 'bf' columns, indexed by HIP
    markdown: list of tuples (hip1, hip2)
    """

    def sph_to_cart(ra_deg, dec_deg): # translates spherical cords to decart
        ra_rad = np.radians(ra_deg)
        dec_rad = np.radians(dec_deg)
        x = np.cos(dec_rad) * np.cos(ra_rad)
        y = np.cos(dec_rad) * np.sin(ra_rad)
        z = np.sin(dec_rad)
        return np.stack([x, y, z], axis=0) # check below:
        # a = [1, 2]
        # b = [3, 4]
        # np.stack(a, b) -> [[1, 2], [3, 4]]

    def get_rotation_matrix(center_ra_deg, center_dec_deg):
        ra0 = np.radians(center_ra_deg)
        dec0 = np.radians(center_dec_deg)

        cz = np.sin(dec0)
        cx = np.cos(dec0) * np.cos(ra0)
        cy = np.cos(dec0) * np.sin(ra0)
        z_axis = np.array([cx, cy, cz])

        up = np.array([0, 0, 1])
        x_axis = np.cross(up, z_axis)     # vectorized due correct direction
        x_axis /= np.linalg.norm(x_axis)
        y_axis = np.cross(z_axis, x_axis)

        return np.vstack([x_axis, y_axis, z_axis])  # shape: (3,3)


    plt.figure(figsize=(7, 7), dpi=100)
    ax = plt.gca()
    ax.set_facecolor('black')
    plt.axis('equal')
    
    center_ra = frame['ra'].mean()
    center_dec = frame['dec'].mean()

    center_ra_deg = center_ra * 15.0
    rotation = get_rotation_matrix(center_ra_deg, center_dec)

    for hip1, hip2 in markdown:
        stars = frame.loc[[hip1, hip2]]
        ra_deg = stars['ra'].values * 15
        dec_deg = stars['dec'].values
        labels = stars['bf'].values

        vectors = sph_to_cart(ra_deg, dec_deg)
        rotated = rotation @ vectors

        if np.all(rotated[2] < 0):
            continue

        x, y = rotated[0], rotated[1]
        plt.plot(x, y, color='white', linewidth=1)
        plt.scatter(x, y, color='white', s=10, edgecolor='white')

        # for xi, yi, label in zip(x, y, labels):
        #     plt.text(xi, yi, label, fontsize=8, color='cyan')

    # plt.gca().invert_xaxis()
    plt.gca().invert_yaxis()

In [ ]:
def plot_constellation_centered(frame, markdown, center_ra, center_dec):
    """
    frame: DataFrame with 'ra', 'dec', 'bf' columns, indexed by HIP
    markdown: list of tuples (hip1, hip2)
    center_ra: float, Right Ascension in hours
    center_dec: float, Declination in degrees
    """

    def sph_to_cart(ra_deg, dec_deg):
        ra_rad = np.radians(ra_deg)
        dec_rad = np.radians(dec_deg)
        x = np.cos(dec_rad) * np.cos(ra_rad)
        y = np.cos(dec_rad) * np.sin(ra_rad)
        z = np.sin(dec_rad)
        return np.stack([x, y, z], axis=0)

    def get_rotation_matrix(center_ra_deg, center_dec_deg):
        ra0 = np.radians(center_ra_deg)
        dec0 = np.radians(center_dec_deg)

        cz = np.sin(dec0)
        cx = np.cos(dec0) * np.cos(ra0)
        cy = np.cos(dec0) * np.sin(ra0)
        z_axis = np.array([cx, cy, cz])

        up = np.array([0, 0, 1])
        x_axis = np.cross(up, z_axis)
        x_axis /= np.linalg.norm(x_axis)
        y_axis = np.cross(z_axis, x_axis)

        return np.vstack([x_axis, y_axis, z_axis])  # shape: (3,3)

    center_ra_deg = center_ra * 15.0
    rotation = get_rotation_matrix(center_ra_deg, center_dec)

    plt.figure(figsize=(7, 7), dpi=100)
    ax = plt.gca()
    ax.set_facecolor('black')
    plt.axis('equal')

    for hip1, hip2 in markdown:
        stars = frame.loc[[hip1, hip2]]
        ra_deg = stars['ra'].values * 15
        dec_deg = stars['dec'].values
        labels = stars['bf'].values

        vectors = sph_to_cart(ra_deg, dec_deg)
        rotated = rotation @ vectors

        if np.all(rotated[2] < 0):
            continue

        x, y = rotated[0], rotated[1]
        plt.plot(x, y, color='white', linewidth=1)
        plt.scatter(x, y, color='white', s=10, edgecolor='white')

        # for xi, yi, label in zip(x, y, labels):
        #     plt.text(xi, yi, label, fontsize=8, color='cyan')

    plt.gca().invert_xaxis()