In [1]:
import pandas as pd
import numpy as np
import scipy
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../naked_df.csv')
df = df.sort_values(by=['con'])
df = df.set_index(['con', 'hip'])
df

                  id        hd  hr   gl   bf proper         ra        dec  \
con hip
And 114642.0  114280       NaN NaN  NaN  NaN    NaN  23.224074  35.762021
    9194.0      9175   11951.0 NaN  NaN  NaN    NaN   1.972931  43.621980
    3251.0      3244    3858.0 NaN  NaN  NaN    NaN   0.690387  28.042635
    117691.0  117323       NaN NaN  NaN  NaN    NaN  23.868756  37.850250
    115461.0  115096       NaN NaN  NaN  NaN    NaN  23.388891  43.101533
...              ...       ...  ..  ...  ...    ...        ...        ...
Vul 97057.0    96750  344787.0 NaN  NaN  NaN    NaN  19.724830  23.177959
    100983.0  100657  334488.0 NaN  NaN  NaN    NaN  20.474322  28.954089
    101743.0  101416  346992.0 NaN  NaN  NaN    NaN  20.621383  23.895299
    98386.0    98075  333327.0 NaN  NaN  NaN    NaN  19.990121  28.241549
    102331.0  102000  197573.0 NaN  NaN  NaN    NaN  20.733344  21.400658

                     dist    mag  spect bayer  flam           lum
con hip
And 114642.0     293.2551   8.65     K0   NaN   NaN  2.596570e+01
    9194.0       343.6426   7.65     A0   NaN   NaN  8.961898e+01
    3251.0       390.6250   7.89     A5   NaN   NaN  9.281112e+01
    117691.0  100000.0000   8.73     M5   NaN   NaN  2.805434e+06
    115461.0     338.9831   9.41     A2   NaN   NaN  1.723455e+01
...                   ...    ...    ...   ...   ...           ...
Vul 97057.0   100000.0000   9.31   F8Ib   NaN   NaN  1.644372e+06
    100983.0     393.7008   8.73  G8III   NaN   NaN  4.349106e+01
    101743.0     434.7826  11.79     A2   NaN   NaN  3.165192e+00
    98386.0      196.4637   9.48     F8   NaN   NaN  5.425003e+00
    102331.0     105.9322   7.18     A2   NaN   NaN  1.312200e+01

[117951 rows x 14 columns]

In [3]:
# 'Com', 'CVn', 'Boo', 'Cir', 'Aps', 'Lup', 'Lib', 'TrA', 'Ser',
# 'Nor', 'CrB', 'Sco', 'Her', 'Oph', 'Ara', 'Pav', 'Sgr', 'CrA',

In [4]:
# ===================================== 1
# Com = Coma Berenecies (волосы Вероники)

In [5]:
Com = df.xs('Com', level='con')
Com = Com.loc[[60742, 64394, 64241]]
Com['con'] = 'Com'

In [6]:
Com.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
64241.0,64037,114378.0,4968.0,Gl 501A,42Alp Com,Diadem,13.166469,17.529431,17.8253,4.32,F5V,Alp,42.0,5.176068,Com
64394.0,64189,114710.0,4983.0,Gl 502,43Bet Com,NaN,13.197904,27.878183,9.1291,4.23,G0V,Bet,43.0,1.475027,Com
60742.0,60554,108381.0,4737.0,NaN,15Gam Com,NaN,12.448966,28.268423,51.2821,4.35,K2IIICN+...,Gam,15.0,41.686938,Com

In [7]:
Com_con = ((60742, 64394), (64394, 64241))

In [8]:
# ===================================== 2
# CVn = Canes Venatici (гончие псы)

In [9]:
CVn = df.xs('CVn', level='con')
CVn = CVn.loc[[61317, 63125]]
CVn['con'] = 'CVn'

In [10]:
CVn.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
63125.0,62925,112413.0,4915.0,NaN,12Alp2CVn,Cor Caroli,12.933807,38.31838,35.1989,2.89,A0spe...,Alp-2,12.0,75.370258,CVn
61317.0,61124,109358.0,4785.0,Gl 475,8Bet CVn,Chara,12.562411,41.35748,8.4395,4.24,G0V,Bet,8.0,1.249683,CVn

In [11]:
CVn_con = ((61317, 63125))

In [12]:
# ===================================== 3
# Boo = Bootes (волопас)

In [13]:
Boo = df.xs('Boo', level='con')
Boo = Boo.loc[[67459, 67927, 69673, 71053, 71075, 73555, 74666, 72105, 71795]]
Boo['con'] = 'Boo'

In [14]:
Boo.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
69673.0,69451,124897.0,5340.0,Gl 541,16Alp Boo,Arcturus,14.261030,19.182410,11.2575,-0.05,K2IIIp,Alp,16.0,115.557996,Boo
73555.0,73327,133208.0,5602.0,NaN,42Bet Boo,Nekkar,15.032436,40.390566,69.0608,3.49,G8III,Bet,42.0,166.878351,Boo
74666.0,74438,135722.0,5681.0,NaN,49Del Boo,NaN,15.258376,33.314833,37.3413,3.46,G8III,Del,49.0,50.164906,Boo
72105.0,71879,129988.0,5505.0,NaN,36Eps Boo,Izar,14.749784,27.074222,62.1118,2.35,A0,Eps,36.0,385.833560,Boo
67927.0,67711,121370.0,5235.0,Gl 534,8Eta Boo,Muphrid,13.911411,18.397717,11.3960,2.68,G0IV,Eta,8.0,9.585174,Boo
71075.0,70851,127762.0,5435.0,NaN,27Gam Boo,Seginus,14.534636,38.308253,26.6099,3.04,A7IIIvar,Gam,27.0,37.497300,Boo
71053.0,70828,127665.0,5429.0,NaN,25Rho Boo,NaN,14.530500,30.371437,49.0918,3.57,K3III,Rho,25.0,78.342964,Boo
67459.0,67246,120477.0,5200.0,NaN,5Ups Boo,NaN,13.824623,15.797905,80.7754,4.05,K5IIIvar,Ups,5.0,136.269920,Boo
71795.0,71569,129246.0,5477.0,NaN,30Zet Boo,NaN,14.685820,13.728300,53.8793,3.78,A3IVn,Zet,30.0,77.767833,Boo

In [15]:
Boo_con = ((67459, 67927), (67927, 69673), (69673, 71053), (71053, 71075), (71075, 73555), (73555, 74666), (74666, 72105), (72105, 69673), (69673, 71795))

In [16]:
# ===================================== 4
# Cir = Circinus (циркуль)

In [17]:
Cir = df.xs('Cir', level='con')
Cir = Cir.loc[[74824, 71908, 75323]]
Cir['con'] = 'Cir'

In [18]:
Cir.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
71908.0,71682,128898.0,5463.0,Gl 560A,Alp Cir,NaN,14.708492,-64.975138,16.5700,3.18,F1Vp,Alp,NaN,12.787923,Cir
74824.0,74595,135379.0,5670.0,Gl 580.1,Bet Cir,NaN,15.291917,-58.801208,30.5530,4.07,A3V,Bet,NaN,19.142559,Cir
75323.0,75094,136415.0,5704.0,NaN,Gam Cir,NaN,15.389625,-59.320787,137.5516,4.48,B5III + F8,Gam,NaN,265.950003,Cir

In [19]:
Cir_con = ((74824, 71908), (71908, 75323))

In [20]:
# ===================================== 5 
# Aps = Apus (райская птица)

In [21]:
Aps = df.xs('Aps', level='con')
Aps = Aps.loc[[72370, 81065, 81852]]
Aps['con'] = 'Aps'

In [22]:
Aps.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
72370.0,72144,129078.0,5470.0,NaN,Alp Aps,NaN,14.797701,-79.044751,136.9863,3.83,K5III,Alp,NaN,479.954425,Aps
81852.0,81602,149324.0,6163.0,NaN,Bet Aps,NaN,16.718126,-77.517435,48.1232,4.23,K0III,Bet,NaN,41.001524,Aps
81065.0,80819,147675.0,6102.0,Gl 626.1,Gam Aps,NaN,16.557609,-78.897148,47.9157,3.86,K0IV SB,Gam,NaN,57.121552,Aps

In [23]:
Aps_con = ((72370, 81065), (81065, 81852))

In [24]:
# ===================================== 6
# Lup = Lupus (волк)

In [25]:
Lup = df.xs('Lup', level='con')
Lup = Lup.loc[[71860, 73273, 75141, 76297, 76552, 74395, 77634, 78384, 78970, 75177, 70576, 71536]]
Lup['con'] = 'Lup'

In [26]:
Lup.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
71860.0,71634,129056.0,5469.0,NaN,Alp Lup,NaN,14.698823,-47.388200,142.4501,2.30,B1.5III,Alp,NaN,2124.222477,Lup
73273.0,73046,132058.0,5571.0,NaN,Bet Lup,NaN,14.975537,-43.133960,117.3709,2.68,B2III,Bet,NaN,1016.716800,Lup
77634.0,77398,141556.0,5883.0,NaN,5Chi Lup,NaN,15.849316,-33.627165,59.8444,3.97,B9.5III-IV,Chi,5.0,80.537844,Lup
75141.0,74912,136298.0,5695.0,NaN,Del Lup,NaN,15.356201,-40.647518,271.0027,3.22,B1.5IV,Del,NaN,3296.097122,Lup
78384.0,78148,143118.0,5948.0,NaN,Eta Lup,NaN,16.002036,-38.396706,135.5014,3.42,B2.5IV,Eta,NaN,685.488226,Lup
76297.0,76065,138690.0,5776.0,NaN,Gam Lup,NaN,15.585681,-41.166757,129.0323,2.80,B2IV,Gam,NaN,1099.512067,Lup
76552.0,76317,139127.0,5797.0,NaN,Ome Lup,NaN,15.634232,-42.567348,67.0241,4.34,K4.5III,Ome,NaN,71.845571,Lup
75177.0,74948,136422.0,5705.0,NaN,Phi1Lup,NaN,15.363440,-36.261376,84.3170,3.57,K5III,Phi-1,NaN,231.206479,Lup
71536.0,71310,128345.0,5453.0,NaN,Rho Lup,NaN,14.631454,-49.425828,96.8992,4.05,B5V,Rho,NaN,196.245632,Lup
70576.0,70353,126354.0,5396.0,NaN,Tau2Lup,NaN,14.436336,-45.379276,97.8474,4.33,A7:+...,Tau-2,NaN,154.596622,Lup
74395.0,74167,134505.0,5649.0,GJ 9512A,Zet Lup,NaN,15.204760,-52.099247,35.9712,3.41,G8III,Zet,NaN,48.752849,Lup
78970.0,78730,144415.0,5991.0,NaN,NaN,NaN,16.121168,-36.755676,54.7945,5.72,F0/F2V,NaN,NaN,13.477210,Lup

In [27]:
Lup_con = ((71860, 73273), (73273, 75141), (75141, 76297), (76297, 76552), (76552, 74395), (74395, 71860),
           (77634, 78384), (78384, 78970), (78970, 77634), (78384, 76297), (75177, 75141), (70576, 71860), (71536, 74395))

In [28]:
# ===================================== 7
# Lib = Libra (весы)

In [29]:
Lib = df.xs('Lib', level='con')
Lib = Lib.loc[[73714, 72622, 74785, 76333, 77853]]
Lib['con'] = 'Lib'

In [30]:
Lib.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
72622.0,72396,130841.0,5531.0,Gl 564.1,9Alp2Lib,Zubenelgenubi,14.847977,-16.041778,23.2396,2.75,A3IV,Alp-2,9.0,37.359409,Lib
74785.0,74556,135742.0,5685.0,NaN,27Bet Lib,Zubeneschamali,15.283449,-9.382917,56.7537,2.61,B8V,Bet,27.0,253.512863,Lib
76333.0,76100,138905.0,5787.0,GJ 3912,38Gam Lib,Zubenelhakrabi,15.592105,-14.789537,50.0250,3.91,K0III,Gam,38.0,59.483977,Lib
73714.0,73486,133216.0,5603.0,NaN,20Sig Lib,Brachium,15.067839,-25.281965,88.4173,3.25,M3/M4III,Sig,20.0,341.350073,Lib
77853.0,77617,142198.0,5908.0,NaN,46The Lib,NaN,15.897093,-16.729293,51.6529,4.13,K0III,The,46.0,51.760683,Lib

In [31]:
Lib_con = ((73714, 72622), (72622, 74785), (74785, 76333), (76333, 77853), (73714, 76333))

In [32]:
# ===================================== 8
# TrA = Triangulum Australe (южный треугольник)

In [33]:
TrA = df.xs('TrA', level='con')
TrA = TrA.loc[[82273, 74946, 77952]]
TrA['con'] = 'TrA'

In [34]:
TrA.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
82273.0,82022,150798.0,6217.0,NaN,Alp TrA,Atria,16.811077,-69.027715,119.7605,1.91,K2IIb-IIIa,Alp,NaN,2151.790570,TrA
77952.0,77716,141891.0,5897.0,Gl 601A,Bet TrA,NaN,15.919083,-63.430727,12.3778,2.83,F2III,Bet,NaN,9.844644,TrA
74946.0,74717,135382.0,5671.0,NaN,Gam TrA,NaN,15.315181,-68.679545,56.3698,2.87,A1V,Gam,NaN,196.788629,TrA

In [35]:
TrA_con = ((82273, 74946), (74946, 77952), (77952, 82273))

In [36]:
# ===================================== 9
# Ser = Serpens (змея)

In [37]:
Ser = df.xs('Ser', level='con')
Ser = Ser.loc[[77516, 77622, 77070, 76276, 77233, 77450, 78072]]
Ser['con'] = 'Ser'

In [38]:
Ser.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
77070.0,76835,140573.0,5854.0,Gl 596.2,24Alp Ser,Unukalhai,15.737798,6.425627,22.6757,2.63,K2III,Alp,24.0,39.737451,Ser
77233.0,76997,141003.0,5867.0,NaN,28Bet Ser,NaN,15.769793,15.421826,47.5511,3.65,A3V,Bet,28.0,68.296744,Ser
76276.0,76044,138917.0,5788.0,NaN,13Del Ser,NaN,15.580041,10.538867,69.9301,3.80,F0IV,Del,13.0,128.587869,Ser
77622.0,77386,141795.0,5892.0,GJ 3921,37Eps Ser,NaN,15.846935,4.477730,21.5983,3.71,A2m,Eps,37.0,13.329075,Ser
78072.0,77836,142860.0,5933.0,Gl 603,41Gam Ser,NaN,15.940882,15.661617,11.2537,3.85,F6V,Gam,41.0,3.179801,Ser
77450.0,77214,141477.0,5879.0,NaN,35Kap Ser,Gudja,15.812327,18.141564,117.0960,4.09,M1III,Kap,35.0,276.184944,Ser
77516.0,77280,141513.0,5881.0,NaN,32Mu Ser,NaN,15.827002,-3.430208,52.0021,3.54,A0V,Mu,32.0,90.364947,Ser

In [39]:
Ser_con = ((77516, 77622), (77622, 77070), (77070, 76276), (76276, 77233), (77233, 77450), (77450, 78072), (78072, 77233))

In [40]:
# ===================================== 10
# Nor = Norma (наугольник)

In [41]:
Nor = df.xs('Nor', level='con')
Nor = Nor.loc[[80582, 78639, 79509, 80000]]
Nor['con'] = 'Nor'

In [42]:
Nor.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
80582.0,80339,147971.0,6115.0,NaN,Eps Nor,NaN,16.453067,-47.554786,162.6016,4.46,B4V,Eps,NaN,378.791304,Nor
78639.0,78400,143546.0,5962.0,NaN,Eta Nor,NaN,16.053579,-49.229695,67.2948,4.65,G8III,Eta,NaN,54.450265,Nor
80000.0,79759,146686.0,6072.0,GJ 9554,Gam2Nor,NaN,16.330687,-50.155508,39.4789,4.01,G8III,Gam-2,NaN,33.790919,Nor
79509.0,79270,145397.0,6024.0,NaN,Kap Nor,NaN,16.224648,-54.630467,131.2336,4.95,G4III,Kap,NaN,157.036280,Nor

In [43]:
Nor_con = ((80582, 78639), (78639, 79509), (79509, 80000), (80000, 80582), (80000, 78639))

In [44]:
# ===================================== 11
# CrB = Corona Borealis (северная корона)

In [45]:
CrB = df.xs('CrB', level='con')
CrB = CrB.loc[[76127, 75695, 76267, 76952, 77512, 78159, 78493]]
CrB['con'] = 'CrB'

In [46]:
CrB.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
76267.0,76035,139006.0,5793.0,NaN,5Alp CrB,Alphecca,15.578128,26.714693,23.0097,2.22,A0V,Alp,5.0,59.703529,CrB
75695.0,75466,137909.0,5747.0,NaN,3Bet CrB,Nusakan,15.463818,29.105703,34.2818,3.66,F0p,Bet,3.0,35.156044,CrB
77512.0,77276,141714.0,5889.0,NaN,10Del CrB,NaN,15.826570,26.068394,52.1376,4.59,G5III-IV,Del,10.0,34.546177,CrB
78159.0,77923,143107.0,5947.0,NaN,13Eps CrB,NaN,15.959794,26.877880,67.8887,4.14,K3III,Eps,13.0,88.633929,CrB
76952.0,76716,140436.0,5849.0,NaN,8Gam CrB,NaN,15.712381,26.295637,44.7828,3.81,A1Vs,Gam,8.0,52.287756,CrB
78493.0,78256,143807.0,5971.0,NaN,14Iot CrB,NaN,16.024047,29.851061,95.6023,4.98,A0p...,Iot,14.0,81.058768,CrB
76127.0,75895,138749.0,5778.0,NaN,4The CrB,NaN,15.548829,31.359133,115.0748,4.14,B6Vnn,The,4.0,254.683025,CrB

In [47]:
CrB_con = ((76127, 75695), (75695, 76267), (76267, 76952), (76952, 77512), (77512, 78159), (78159, 78493))

In [48]:
# ===================================== 12
# Sco = Scorpius (скорпион)

In [49]:
Sco = df.xs('Sco', level='con')
Sco = Sco.loc[[85927, 86670, 87073, 86228, 84143, 82671, 82514, 82396, 81266, 80763, 78820, 78401, 78265]]
Sco['con'] = 'Sco'

In [50]:
Sco.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
80763.0,80519,148478.0,6134.0,NaN,21Alp Sco,Antares,16.490128,-26.432002,169.7793,1.06,M1Ib + B2.5V,Alp,21.0,9453.660460,Sco
78820.0,78580,144217.0,5984.0,NaN,8Bet1Sco,Acrab,16.090620,-19.805453,123.9157,2.56,B0.5V,Bet-1,8.0,1265.901749,Sco
78401.0,78165,143275.0,5953.0,NaN,7Del Sco,Dschubba,16.005557,-22.621710,150.6024,2.29,B0.2IV,Del,7.0,2396.624529,Sco
82396.0,82144,151680.0,6241.0,NaN,26Eps Sco,Larawag,16.836080,-34.293232,19.5351,2.29,K2IIIb,Eps,26.0,40.327379,Sco
84143.0,83885,155203.0,6380.0,Gl 657,Eta Sco,NaN,17.202552,-43.239189,22.5276,3.32,F3p,Eta,NaN,20.777821,Sco
87073.0,86804,161471.0,6615.0,NaN,Iot1Sco,NaN,17.793078,-40.126997,591.7160,2.99,F3Ia,Iot-1,NaN,19426.743230,Sco
86670.0,86403,160578.0,6580.0,NaN,Kap Sco,NaN,17.708132,-39.029983,148.1481,2.39,B1.5III,Kap,NaN,2114.462562,Sco
85927.0,85665,158926.0,6527.0,NaN,35Lam Sco,Shaula,17.560145,-37.103821,175.1313,1.62,B1.5IV+...,Lam,35.0,6008.969505,Sco
82514.0,82263,151890.0,6247.0,NaN,Mu 1Sco,Xamidimura,16.864509,-38.047380,153.6098,3.00,B1.5IV + B,Mu-1,NaN,1296.582035,Sco
78265.0,78029,143018.0,5944.0,NaN,6Pi Sco,Fang,15.980865,-26.114105,179.5332,2.89,B1V + B2V,Pi,6.0,1960.649667,Sco
81266.0,81020,149438.0,6165.0,NaN,23Tau Sco,Paikauhale,16.598043,-28.216016,145.3488,2.82,B0V,Tau,23.0,1370.250597,Sco
86228.0,85965,159532.0,6553.0,NaN,The Sco,Sargas,17.621980,-42.997824,92.0810,1.86,F1II,The,NaN,1331.680376,Sco
82671.0,82419,152236.0,6262.0,NaN,Zet1Sco,NaN,16.899924,-42.362025,787.4016,4.70,B1Iae,Zet-1,NaN,7118.688673,Sco

In [51]:
Sco_con = ((85927, 86670), (86670, 87073), (87073, 86228), (86228, 84143), (84143, 82671), (82671, 82514), (82514, 82396), (82396, 81266), (81266, 80763), (80763, 78820),
           (80763, 78401), (80763, 78265))

In [52]:
# ===================================== 13
# Her = Hercules (геркулес)

In [53]:
Her = df.xs('Her', level='con')
Her = Her.loc[[84380, 83207, 81693, 81833, 86414, 87808, 85112, 84606, 77760, 79992, 81126, 80170, 80816, 88794, 87933, 86974, 85693, 84379]]
Her['con'] = 'Her'

In [54]:
Her.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
80816.0,80571,148856.0,6148.0,NaN,27Bet Her,Kornephoros,16.503668,21.489613,42.6621,2.78,G8III,Bet,27.0,122.461620,Her
77760.0,77524,142373.0,5914.0,Gl 602,1Chi Her,NaN,15.877903,42.451518,15.8932,4.60,F9V,Chi,1.0,3.179801,Her
84379.0,84121,156164.0,6410.0,GJ 3995A,65Del Her,Sarin,17.250531,24.839204,23.0362,3.12,A3IVv SB,Del,65.0,26.109587,Her
83207.0,82952,153808.0,6324.0,NaN,58Eps Her,NaN,17.004827,30.926405,47.5285,3.92,A0V,Eps,58.0,53.210826,Her
81833.0,81583,150997.0,6220.0,NaN,44Eta Her,NaN,16.714933,38.922254,33.3111,3.48,G8III-IV,Eta,44.0,39.192232,Her
80170.0,79928,147547.0,6095.0,NaN,20Gam Her,NaN,16.365338,19.153130,59.0667,3.74,A9III,Gam,20.0,97.006313,Her
86414.0,86148,160762.0,6588.0,NaN,85Iot Her,NaN,17.657747,46.006332,139.4700,3.82,B3V SB,Iot,85.0,502.111305,Her
85693.0,85433,158899.0,6526.0,NaN,76Lam Her,Maasym,17.512308,26.110645,113.2503,4.41,K3IIIvar,Lam,76.0,192.309173,Her
86974.0,86705,161797.0,6623.0,Gl 695A,86Mu Her,NaN,17.774319,27.720676,8.3105,3.42,G5IV,Mu,86.0,2.577508,Her
88794.0,88517,166014.0,6779.0,NaN,103Omi Her,NaN,18.125708,28.762488,103.6269,3.84,B9.5V,Omi,103.0,272.144775,Her
84380.0,84122,156283.0,6418.0,NaN,67Pi Her,NaN,17.250788,36.809162,115.4734,3.16,K3IIvar,Pi,67.0,632.120682,Her
85112.0,84853,157778.0,6484.0,NaN,75Rho Her,NaN,17.394708,37.145946,120.6273,4.15,B9.5III,Rho,75.0,277.204324,Her
81126.0,80880,149630.0,6168.0,NaN,35Sig Her,NaN,16.568384,42.437041,96.5251,4.20,B9Vvar,Sig,35.0,169.511825,Her
79992.0,79750,147394.0,6092.0,NaN,22Tau Her,NaN,16.329011,46.313366,94.2507,3.91,B5IV,Tau,22.0,211.057116,Her
87808.0,87537,163770.0,6695.0,NaN,91The Her,NaN,17.937550,37.250539,230.9469,3.86,K1IIvar,The,91.0,1328.005886,Her
87933.0,87661,163993.0,6703.0,NaN,92Xi Her,NaN,17.962744,29.247880,41.9463,3.70,K0III,Xi,92.0,50.722424,Her
81693.0,81444,150680.0,6212.0,Gl 635A,40Zet Her,NaN,16.688113,31.602726,10.7158,2.81,F9IV,Zet,40.0,7.516229,Her
84606.0,84348,156729.0,6436.0,NaN,69 Her,NaN,17.294517,37.291498,53.7924,4.64,A2V,NaN,69.0,35.123679,Her

In [55]:
Her_con = ((84380, 83207), (83207, 81693), (81693, 81833), (81833, 84380),
           (86414, 87808), (87808, 85112), (85112, 84606), (84606, 84380),
           (77760, 79992), (79992, 81126), (81126, 81833),
           (80170, 80816), (80816, 81693),
           (88794, 87933), (87933, 86974), (86974, 85693), (85693, 84379), (85693, 83207))

In [56]:
# ===================================== 14
# Oph = Ophiuchus (змееносец)

In [57]:
Oph = df.xs('Oph', level='con')
Oph = Oph.loc[[85755, 84012, 81377, 79882, 83000, 86032, 86742]]
Oph['con'] = 'Oph'

In [58]:
Oph.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
86032.0,85769,159561.0,6556.0,Gl 681,55Alp Oph,Rasalhague,17.582241,12.560035,14.8965,2.08,A5III,Alp,55.0,28.444611,Oph
86742.0,86475,161096.0,6603.0,NaN,60Bet Oph,Cebalrai,17.724543,4.567303,25.0941,2.76,K2III,Bet,60.0,43.171784,Oph
79882.0,79640,146791.0,6075.0,GJ 3949,2Eps Oph,Yed Posterior,16.305358,-4.692511,32.6371,3.23,G8III,Eps,2.0,47.380539,Oph
84012.0,83755,155125.0,6378.0,Gl 656.1A,35Eta Oph,Sabik,17.172968,-15.724910,27.0929,2.43,A2.5Va,Eta,35.0,68.171053,Oph
83000.0,82745,153210.0,6299.0,NaN,27Kap Oph,NaN,16.961139,9.375033,28.0426,3.19,K2IIIvar,Kap,27.0,36.274380,Oph
81377.0,81130,149757.0,6175.0,NaN,13Zet Oph,NaN,16.619316,-10.567090,112.2334,2.54,O9.5V,Zet,13.0,1057.791322,Oph
85755.0,85494,158643.0,6519.0,NaN,51 Oph,NaN,17.523598,-23.962643,124.3781,4.78,A0V,NaN,51.0,165.044099,Oph

In [59]:
Oph_con = ((85755, 84012), (84012, 81377), (81377, 79882), (79882, 83000), (83000, 86032), (86032, 86742), (86742, 84012))

In [60]:
# ===================================== 15
# Ara = Ara (жертвенник)

In [61]:
Ara = df.xs('Ara', level='con')
Ara = Ara.loc[[85727, 82363, 83081, 85792, 88714, 85258, 85267]]
Ara['con'] = 'Ara'

In [62]:
Ara.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
85792.0,85530,158427.0,6510.0,NaN,Alp Ara,NaN,17.530695,-49.876145,81.9672,2.84,B2Vne,Alp,NaN,427.759831,Ara
85258.0,84999,157244.0,6461.0,NaN,Bet Ara,NaN,17.421665,-55.529884,198.0198,2.84,K3Ib-II,Bet,NaN,2498.043519,Ara
85727.0,85467,158094.0,6500.0,NaN,Del Ara,NaN,17.518318,-60.683848,60.6796,3.60,B8V,Del,NaN,116.412603,Ara
82363.0,82112,151249.0,6229.0,NaN,Eta Ara,NaN,16.829760,-59.041378,91.7431,3.77,K5III,Eta,NaN,227.614539,Ara
85267.0,85008,157246.0,6462.0,NaN,Gam Ara,NaN,17.423239,-56.377727,341.2969,3.31,B1Ib,Gam,NaN,4812.824219,Ara
88714.0,88439,165024.0,6743.0,NaN,The Ara,NaN,18.110520,-50.091477,249.3766,3.65,B2Ib,The,NaN,1877.586699,Ara
83081.0,82826,152786.0,6285.0,GJ 9581,Zet Ara,NaN,16.977006,-55.990141,149.0313,3.12,K5III,Zet,NaN,1092.446053,Ara

In [63]:
Ara_con = ((85727, 82363), (82363, 83081), (83081, 85792), (85792, 88714), (88714, 85258), (85258, 85267), (85267, 85727))

In [64]:
# ===================================== 16
# Pav = Pavo (павлин)

In [65]:
Pav = df.xs('Pav', level='con')
Pav = Pav.loc[[100751, 105858, 102395, 99240, 93015, 92609, 88866, 86929, 90098, 98495, 91792]]
Pav['con'] = 'Pav'

In [66]:
Pav.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
100751.0,100425,193924.0,7790.0,NaN,Alp Pav,Peacock,20.427459,-56.735090,54.8246,1.94,B2IV,Alp,NaN,438.530698,Pav
102395.0,102064,197051.0,7913.0,NaN,Bet Pav,NaN,20.749314,-66.203212,41.4250,3.42,A5IV,Bet,NaN,64.032432,Pav
99240.0,98924,190248.0,7665.0,Gl 780,Del Pav,NaN,20.145157,-66.182068,6.1084,3.55,G5IV-Vvar,Del,NaN,1.235947,Pav
98495.0,98184,188228.0,7590.0,NaN,Eps Pav,NaN,20.009845,-72.910504,32.2165,3.97,A0V,Eps,NaN,23.334581,Pav
86929.0,86661,160635.0,6582.0,NaN,Eta Pav,NaN,17.762221,-64.723871,107.9914,3.61,K1III,Eta,NaN,365.426468,Pav
105858.0,105519,203608.0,8181.0,Gl 827,Gam Pav,NaN,21.440705,-65.366198,9.2618,4.21,F6V,Gam,NaN,1.545966,Pav
93015.0,92723,174694.0,7107.0,NaN,Kap Pav,NaN,18.949177,-67.233495,153.3742,4.40,F5Ib-II:,Kap,NaN,356.122981,Pav
92609.0,92319,173948.0,7074.0,NaN,Lam Pav,NaN,18.870288,-62.187593,438.5965,4.22,B2II-III,Lam,NaN,3435.579479,Pav
88866.0,88589,165040.0,6745.0,NaN,Pi Pav,NaN,18.143000,-63.668553,39.8565,4.33,Am,Pi,NaN,25.633033,Pav
90098.0,89819,168339.0,6855.0,NaN,Xi Pav,NaN,18.387117,-61.493901,143.6782,4.35,M1III SB,Xi,NaN,327.189984,Pav
91792.0,91507,171759.0,6982.0,NaN,Zet Pav,NaN,18.717260,-71.428113,66.9792,4.01,K2III,Zet,NaN,97.274722,Pav

In [67]:
Pav_con = ((100751, 105858), (105858, 102395), (102395, 99240), (99240, 93015), (93015, 92609), (92609, 88866), (88866, 86929),
           (90098, 88866), (90098, 92609), (100751, 99240), (98495, 91792), (98495, 99240), (91792, 93015))

In [68]:
# ===================================== 17
# Sgr = Sagittarius (стрелец)

In [69]:
Sgr = df.xs('Sgr', level='con')
Sgr = Sgr.loc[[95294, 98032, 98412, 98688, 96406, 93864, 95347, 95168, 94820, 93683, 93085, 92855, 89341, 90496, 92041, 93506, 89931, 90185, 89642, 88635, 87072]]
Sgr['con'] = 'Sgr'

In [70]:
Sgr.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
95347.0,95052,181869.0,7348.0,NaN,Alp Sgr,Rukbat,19.398103,-40.615940,55.7414,3.96,B8V,Alp,NaN,7.053424e+01,Sgr
95294.0,94999,181623.0,7343.0,NaN,Bet2Sgr,Arkab Posterior,19.386976,-44.799778,41.1353,4.27,F2III,Bet-2,NaN,2.886689e+01,Sgr
89931.0,89653,168454.0,6859.0,NaN,19Del Sgr,Kaus Media,18.349900,-29.828103,106.6098,2.72,K3III,Del,19.0,8.083510e+02,Sgr
90185.0,89906,169022.0,6879.0,NaN,20Eps Sgr,Kaus Australis,18.402868,-34.384616,43.9367,1.79,B9.5III,Eps,20.0,3.232958e+02,Sgr
89642.0,89364,167618.0,6832.0,NaN,Eta Sgr,NaN,18.293793,-36.761686,44.7427,3.10,M2III,Eta,NaN,1.003691e+02,Sgr
88635.0,88361,165135.0,6746.0,NaN,10Gam2Sgr,Alnasl,18.096803,-30.424091,29.7000,2.98,K0III,Gam-2,10.0,4.938556e+01,Sgr
98032.0,97721,188114.0,7581.0,NaN,Iot Sgr,NaN,19.921026,-41.868288,55.7414,4.12,K0III,Iot,NaN,6.086954e+01,Sgr
90496.0,90217,169916.0,6913.0,Gl 713.1,22Lam Sgr,Kaus Borealis,18.466179,-25.421700,23.9693,2.82,K1IIIb,Lam,22.0,3.725632e+01,Sgr
89341.0,89064,166937.0,6812.0,NaN,13Mu Sgr,Polis,18.229392,-21.058834,100000.0000,3.84,B2III:,Mu,13.0,2.535129e+08,Sgr
93683.0,93388,177241.0,7217.0,GJ 9641,39Omi Sgr,NaN,19.078050,-21.741496,43.5540,3.76,K0III,Omi,39.0,5.176068e+01,Sgr
92041.0,91754,173300.0,7039.0,NaN,27Phi Sgr,NaN,18.760940,-26.990778,73.3676,3.17,B8.5III,Phi,27.0,2.530463e+02,Sgr
95168.0,94873,181577.0,7340.0,GJ 4107,44Rho1Sgr,NaN,19.361211,-17.847197,38.9257,3.92,F0III/IV,Rho-1,44.0,3.567796e+01,Sgr
92855.0,92564,175191.0,7121.0,NaN,34Sig Sgr,Nunki,18.921090,-26.296722,69.8324,2.05,B2.5V,Sig,34.0,6.426877e+02,Sgr
93864.0,93569,177716.0,7234.0,GJ 9643,40Tau Sgr,NaN,19.115670,-27.670423,37.2856,3.32,K1/K2III,Tau,40.0,5.691150e+01,Sgr
98412.0,98101,189103.0,7623.0,NaN,The1Sgr,NaN,19.995605,-35.276305,158.9825,4.37,B2.5IV,The-1,NaN,3.933689e+02,Sgr
93085.0,92793,175775.0,7150.0,NaN,37Xi 2Sgr,NaN,18.962167,-21.106654,111.9821,3.52,G8/K0II/III,Xi-2,37.0,4.269726e+02,Sgr
93506.0,93213,176687.0,7194.0,NaN,38Zet Sgr,Ascella,19.043532,-29.880105,27.0416,2.60,A3IV,Zet,38.0,5.807644e+01,Sgr
98688.0,98375,189763.0,7650.0,NaN,62 Sgr,NaN,20.044299,-27.709845,137.5516,4.43,M4III,NaN,62.0,2.784838e+02,Sgr
96406.0,96104,184552.0,7431.0,NaN,51 Sgr,NaN,19.600459,-24.719081,90.2527,5.64,A1m...,NaN,51.0,3.933689e+01,Sgr
94820.0,94525,180540.0,7304.0,NaN,43 Sgr,NaN,19.293911,-18.952908,147.7105,4.88,K0III,NaN,43.0,2.122267e+02,Sgr
87072.0,86803,161592.0,6616.0,NaN,3 Sgr,NaN,17.792674,-27.830788,302.1148,4.53,F7II,NaN,3.0,1.225745e+03,Sgr

In [71]:
Sgr_con = ((95294, 98032), (98032, 98412), (98412, 98688), (98688, 96406), (96406, 93864), (95347, 98032),
           (95168, 94820), (94820, 93683), (93683, 93085), (93085, 92855), (89341, 90496), (90496, 92041), (92041, 93506), (93506, 93864), (92041, 92855),
           (89931, 90185), (90185, 89642), (90496, 89931), (89931, 92041), (90185, 93506), (90185, 88635), (88635, 87072))

In [72]:
# ===================================== 18
# CrA = Corona Australis (южная корона)

In [73]:
CrA = df.xs('CrA', level='con')
CrA = CrA.loc[[90887, 91875, 92989, 93174, 93825, 94114, 94160, 94005, 93542, 92953]]
CrA['con'] = 'CrA'

In [74]:
CrA.sort_values(by='bayer')

,id,hd,hr,gl,bf,proper,ra,dec,dist,mag,spect,bayer,flam,lum,con
hip,,,,,,,,,,,,,,,
94114.0,93819,178253.0,7254.0,NaN,Alp CrA,Meridiana,19.157869,-37.904474,38.4320,4.11,A0/A1V,Alp,NaN,29.187708,CrA
94160.0,93865,178345.0,7259.0,NaN,Bet CrA,NaN,19.167154,-39.340796,145.3488,4.10,K0II/IIICN.,Bet,NaN,421.502350,CrA
94005.0,93710,177873.0,7242.0,NaN,Del CrA,NaN,19.139156,-40.496703,54.7345,4.57,K1III,Del,NaN,38.761449,CrA
93174.0,92881,175813.0,7152.0,NaN,Eps CrA,NaN,18.978721,-37.107357,30.1841,4.83,F3IV/V,Eps,NaN,9.281112,CrA
93825.0,93530,177474.0,7226.0,Gl 743.1A,Gam CrA,NaN,19.106971,-37.063437,17.3040,4.23,F7IV-V,Gam,NaN,5.301515,CrA
91875.0,91589,172777.0,7021.0,NaN,Lam CrA,NaN,18.729706,-38.323441,62.9327,5.11,A0/A1V,Lam,NaN,31.160183,CrA
93542.0,93248,176638.0,7188.0,NaN,Zet CrA,NaN,19.051907,-42.095105,59.2066,4.74,A0Vn,Zet,NaN,38.797166,CrA
90887.0,90605,170642.0,6942.0,NaN,NaN,NaN,18.539257,-39.704001,70.2741,5.16,A3V,NaN,NaN,37.119319,CrA
92989.0,92697,175362.0,7129.0,NaN,NaN,NaN,18.944582,-37.343241,131.9261,5.36,B3V,NaN,NaN,108.842874,CrA
92953.0,92661,175219.0,7122.0,NaN,NaN,NaN,18.938044,-42.710676,90.5797,5.35,G6III-IV,NaN,NaN,51.760683,CrA

In [75]:
CrA_con = ((90887, 91875), (91875, 92989), (92989, 93174), (93174, 93825), (93825, 94114), (94114, 94160), (94160, 94005), (94005, 93542), (93542, 92953))

!CONCLUSION!

!CONCLUSION!

!CONCLUSION!

In [76]:
# 'Com', 'CVn', 'Boo', 'Cir', 'Aps', 'Lup', 'Lib', 'TrA', 'Ser',
# 'Nor', 'CrB', 'Sco', 'Her', 'Oph', 'Ara', 'Pav', 'Sgr', 'CrA',

In [77]:
part_5_df = pd.concat([Com, CVn, Boo, Cir, Aps, Lup, Lib, TrA, Ser, Nor, CrB, Sco, Her, Oph, Ara, Pav, Sgr, CrA])
part_5_df['hip'] = part_5_df.index
part_5_df.to_csv('part_5_df.csv', index=False)

In [ ]:
Com_con = ((60742, 64394), (64394, 64241))
CVn_con = ((61317, 63125))
Boo_con = ((67459, 67927), (67927, 69673), (69673, 71053), (71053, 71075), (71075, 73555), (73555, 74666), (74666, 72105), (72105, 69673), (69673, 71795))
Cir_con = ((74824, 71908), (71908, 75323))
Aps_con = ((72370, 81065), (81065, 81852))
Lup_con = ((71860, 73273), (73273, 75141), (75141, 76297), (76297, 76552), (76552, 74395), (74395, 71860),
           (77634, 78384), (78384, 78970), (78970, 77634), (78384, 76297), (75177, 75141), (70576, 71860), (71536, 74395))
Lib_con = ((73714, 72622), (72622, 74785), (74785, 76333), (76333, 77853), (73714, 76333))
TrA_con = ((82273, 74946), (74946, 77952), (77952, 82273))
Ser_con = ((77516, 77622), (77622, 77070), (77070, 76276), (76276, 77233), (77233, 77450), (77450, 78072), (78072, 77233))
Nor_con = ((80582, 78639), (78639, 79509), (79509, 80000), (80000, 80582), (80000, 78639))
CrB_con = ((76127, 75695), (75695, 76267), (76267, 76952), (76952, 77512), (77512, 78159), (78159, 78493))
Sco_con = ((85927, 86670), (86670, 87073), (87073, 86228), (86228, 84143), (84143, 82671), (82671, 82514), (82514, 82396), (82396, 81266), (81266, 80763), (80763, 78820),
           (80763, 78401), (80763, 78265))
Her_con = ((84380, 83207), (83207, 81693), (81693, 81833), (81833, 84380),
           (86414, 87808), (87808, 85112), (85112, 84606), (84606, 84380),
           (77760, 79992), (79992, 81126), (81126, 81833),
           (80170, 80816), (80816, 81693),
           (88794, 87933), (87933, 86974), (86974, 85693), (85693, 84379), (85693, 83207))
Oph_con = ((85755, 84012), (84012, 81377), (81377, 79882), (79882, 83000), (83000, 86032), (86032, 86742), (86742, 84012))
Ara_con = ((85727, 82363), (82363, 83081), (83081, 85792), (85792, 88714), (88714, 85258), (85258, 85267), (85267, 85727))
Pav_con = ((100751, 105858), (105858, 102395), (102395, 99240), (99240, 93015), (93015, 92609), (92609, 88866), (88866, 86929),
           (90098, 88866), (90098, 92609), (100751, 99240), (98495, 91792), (98495, 99240), (91792, 93015))
Sgr_con = ((95294, 98032), (98032, 98412), (98412, 98688), (98688, 96406), (96406, 93864), (95347, 98032),
           (95168, 94820), (94820, 93683), (93683, 93085), (93085, 92855), (89341, 90496), (90496, 92041), (92041, 93506), (93506, 93864), (92041, 92855),
           (89931, 90185), (90185, 89642), (90496, 89931), (89931, 92041), (90185, 93506), (90185, 88635), (88635, 87072))
CrA_con = ((90887, 91875), (91875, 92989), (92989, 93174), (93174, 93825), (93825, 94114), (94114, 94160), (94160, 94005), (94005, 93542), (93542, 92953))